### ISSUE TITLE
Error when using theta vector longer than 2 in the cffilter

### ISSUE THREAD

**Issue by pgg1309** [mbalcilar/mFilter#1]
Hi @mbalcilar 
I got an error running `cffilter()` with a theta vector of size 3 or longer. 
From my understanding `nq` equals the length of the theta vector minus one, so in my case `nq = 2`

But in the code below, `R0` issues an warning. `B[1]*cc[1] `is a scalar. But both `B[2:3]` and `cc[2:3]` are vectors. They are multiplied element by element producing another vector.  Transpose does not change anything since it is a one dimensional vector. As a result, `R0` is a vector of dimension 2 or higher. However, it is then assigned to `R[1]` which expects a scalar -- and therefore R issues a warning message.

I am not familiar with the details of the filter implementation, so I am not able to understand what the 
`2*t(B[2:(nq+1)])*cc[2:(nq+1)]` part is supposed to do. 

Can you help me with that ?

Thanks and congrats for the very useful package !

if(nq > 0)
    {
        R0 = B[1]*cc[1] + 2*t(B[2:(nq+1)])*cc[2:(nq+1)]
        R[1] = pi*R0
        for(i in 2:n)
        {
            dj = Bge(i-2,nq,B,cc)
            R[i] = R[i-1] - dj
        }
    }

**Comment by pgg1309** [comment]
Hi @mbalcilar 
I looked at the original matlab code and figured out what needs to be changed. 
You should substitute 

2t(B[2:(nq+1)])cc[2:(nq+1)]

by
2 * crosprod(B[2:(nq+1), cc[2:(nq+1)])

I am not familiar with github, otherwise I would start a pull request with the suggested fix. 

Thanks again for sharing all your work.

**Comment by mbalcilar** [comment]
Fixed. Please do devtools::install_github("mbalcilar/mFilter")
